# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Theme for henning.tegner.kim
name: Henning Tegner
email: henning@tegner.kim
copyrightFrom: 2015
copyrightTo: 2019
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henning.tegner.kim" # the base hostname & protocol for your site, e.g. http://example.com
twitter_address: https://twitter.com/hktegner
facebook_address: https://fb.com/hktegner
linkedin_address: https://linkedin.com/in/hktegner
gitlab_address: https://gitlab.com/hktegner
email_address: mailto:henning@tegner.kim

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock

# Defaults for subsets of files
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _rocket
  - scope:
      path: ""
      type: rocket
    values:
      layout: article
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  # _software
  - scope:
      path: ""
      type: software
    values:
      layout: article
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true

# Collections
collections:
  # Java Rocket Launcher Tutorial
  rocket:
    output: true
    label: rocket
    permalink: /:collection/:path/
  # Portfolio of software
  software:
    output: true
    label: software
    permalink: /:collection/:path/
